from __future__ import annotations

import os
from pathlib import Path


distribution_name = "pin"
package_name = "pinocchio"
version = os.environ["PKG_VERSION"]
site_packages = Path(os.environ["SP_DIR"])
dist_info_dir = site_packages / f"{distribution_name}-{version}.dist-info"

dist_info_dir.mkdir(parents=True, exist_ok=True)

(dist_info_dir / "METADATA").write_text(
    "\n".join(
        [
            "Metadata-Version: 2.1",
            f"Name: {distribution_name}",
            f"Version: {version}",
            "Summary: Pinocchio Python package metadata generated by conda-forge",
            "",
        ]
    ),
    encoding="utf-8",
)
(dist_info_dir / "INSTALLER").write_text("conda\n", encoding="utf-8")
(dist_info_dir / "top_level.txt").write_text(f"{package_name}\n", encoding="utf-8")
