{% set name = "pinocchio" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6a7e6f6f6e3f175dd7010aa998a018f88d712477caa6c41f6ae038310c2fd7d
  patches:
  # circumvent boost problem on windows with clang-cl
    - patches/0003-do-not-use-cmake-boost-policy-CMP0167.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - ninja  # [win]
    - libgomp       # [linux]
    - llvm-openmp   # [osx]
  host:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - libboost-devel
    - libboost-python-devel
    - python
    - numpy
    - casadi
    - qhull
    - qhull-static  # [not win]
    - console_bridge
  run:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - python
    - {{ pin_compatible('numpy') }}
    - casadi
    - qhull
    - qhull-static  # [not win]
    - console_bridge
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}_default${SHLIB_EXT}  # [not win]
  imports:
    - pinocchio

about:
  home: http://github.com/stack-of-tasks/pinocchio
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives
  dev_url: https://github.com/stack-of-tasks/pinocchio

extra:
  recipe-maintainers:
    - fabinsch
    - jorisv
    - jcarpent
    - wolfv
    - ymontmarin
