{% set name = "pinocchio" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: a86ea06a7b4447d00cc46ed541a105f686957400eebb51b25aa41a93c08d855c
  patches:
  # circumvent boost problem on windows with clang-cl
    - patches/0003-do-not-use-cmake-boost-policy-CMP0167.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - ninja  # [win]
    - libgomp       # [linux]
    - llvm-openmp   # [osx]
  host:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - libboost-devel
    - libboost-python-devel
    - python
    # On Windows, Numpy 2.0 don't allow to export the PY_ARRAY_UNIQUE_SYMBOL.
    # This has been fixed in Numpy 2.1.
    - numpy >=2.1      # [win and py>=310]
    # Unfortunatly, Numpy 2.1 is not distributed with Python 3.9.
    # We are forced to use Numpy 1 in this case.
    - numpy >=1.19,<2  # [win and py<310]
    - numpy            # [not win]
    - casadi
    - qhull
    - qhull-static  # [not win]
    - console_bridge
  run:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - python
    - casadi
    - qhull
    - qhull-static  # [not win]
    - console_bridge
    - numpy >=2.1                    # [win and py>=310]
    - {{ pin_compatible('numpy') }}  # [win and py<310]
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}_default${SHLIB_EXT}  # [not win]
  imports:
    - pinocchio

about:
  home: http://github.com/stack-of-tasks/pinocchio
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives
  dev_url: https://github.com/stack-of-tasks/pinocchio

extra:
  recipe-maintainers:
    - fabinsch
    - jorisv
    - jcarpent
    - wolfv
    - ymontmarin
