{% set name = "pinocchio" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e49f3d92e303fe109bc8b329513708a03cdb734a90cb7734821ed2978de8d10
  patches:
    # Fix PyPy support (https://github.com/stack-of-tasks/pinocchio/pull/2274)
    - patches/0001-cmake-Turn-BUILD_WITH_LIBPYTHON-OFF-when-building-wi.patch
    # Fix cross build with hpp-fcl (https://github.com/stack-of-tasks/pinocchio/pull/2288)
    - patches/0002-cmake-Always-suppose-hpp-fcl-Python-binding-are-pres.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - ninja  # [win]
    - libgomp       # [linux]
    - llvm-openmp   # [osx]
  host:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - libboost-devel
    - libboost-python-devel
    - python
    - numpy
    - casadi
  run:
    - eigen
    - eigenpy
    - urdfdom
    - hpp-fcl
    - python
    - {{ pin_compatible('numpy') }}
    - casadi
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}_default${SHLIB_EXT}  # [not win]
  imports:
    - pinocchio

about:
  home: http://github.com/stack-of-tasks/pinocchio
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.LESSER
  summary: A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives
  dev_url: https://github.com/stack-of-tasks/pinocchio

extra:
  recipe-maintainers:
    - jorisv
    - jcarpent
    - wolfv
    - ymontmarin
