bot:
  automerge: true
build_platform:
  osx_64: osx_arm64
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
# We use namespace large CPU runners
# https://conda-forge.org/docs/reference/runners/#namespaceso
provider:
  linux_64: github_actions
  linux_aarch64: github_actions
  osx_64: github_actions
  osx_arm64: github_actions
  win_64: github_actions
test: native_and_emulated
